language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.7
    - os: linux
      dist: focal
      addons:
        apt:
          packages: ['lcov', 'libboost-system1.71-dev', 'libboost-test1.71-dev', 'libboost-program-options1.71-dev', 'libcurl4-openssl-dev']

install:
  - script/travis_ci_setup.sh

before_script:
  - cd $TRAVIS_BUILD_DIR; mkdir build; cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ..;
    else cmake .. -DCMAKE_BUILD_TYPE=Debug; fi;
  - make -j
  - ctest -V

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}/build
      lcov --directory . --capture --output-file coverage.info
      lcov --remove coverage.info '/opt/*' '/usr/*' --output-file coverage.info
      lcov --list coverage.info
      bash <(curl -s https://codecov.io/bash) || echo "No coverage reports"
    fi;
