language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode12
      name: "osx xcode 12"

    - os: linux
      dist: focal
      name: "linux with boost"
      env: CODECOV=true
      addons:
        apt:
          packages: ['lcov', 'libboost-system1.71-dev', 'libboost-test1.71-dev', 'libboost-program-options1.71-dev', 'libcurl4-openssl-dev']
      after_success:
        ${TRAVIS_BUILD_DIR}/script/travis_post_codecov.sh

    - os: linux
      dist: focal
      name: "linux without boost"
      env: NO_BOOST=true

    - os: linux
      dist: focal
      name: "conan with boost"
      script:
        - script/travis_ci_conan_build.sh

    - os: linux
      dist: focal
      name: "conan without boost"
      env: NO_BOOST=true
      script:
        - script/travis_ci_conan_build.sh

install:
  - script/travis_ci_setup_influxdb.sh

script:
  - mkdir build && cd build
  - if [[ -n ${CODECOV+x} ]]; then cmake -DINFLUXCXX_COVERAGE=ON ..; else cmake ..; fi;
  - make -j
  - if [[ -z ${NO_BOOST+x} ]]; then ctest -V; fi
