language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.7
    - os: linux
      dist: focal
      env: CODECOV=true
      addons:
        apt:
          packages: ['lcov', 'libboost-system1.71-dev', 'libboost-test1.71-dev', 'libboost-program-options1.71-dev', 'libcurl4-openssl-dev']

install:
  - script/travis_ci_setup.sh

before_script:
  - cd $TRAVIS_BUILD_DIR; mkdir build; cd build

script:
  - if [[ -n ${CODECOV+x} ]]; then cmake -DCMAKE_BUILD_TYPE=Debug ..;
    else cmake ..; fi;
  - make -j
  - ctest -V

after_success:
  - if [[ -n ${CODECOV+x} ]]; then script/travis_codecov_post.sh; fi
