language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.7
    - os: linux
      dist: focal
      env: CODECOV=true
      addons:
        apt:
          packages: ['lcov', 'libboost-system1.71-dev', 'libboost-test1.71-dev', 'libboost-program-options1.71-dev', 'libcurl4-openssl-dev']
    - os: linux
      dist: focal
      env: NO_BOOST=true
    - os: linux
      dist: focal
      env: CONAN=true
      script:
        - pip install -U --user conan
        - conan profile new default --detect
        - conan profile update settings.compiler.libcxx=libstdc++11 default
        - conan create -o influxdb-cxx:tests=True ${TRAVIS_BUILD_DIR}

install:
  - script/travis_ci_setup_influxdb.sh

before_script:
  - cd ${TRAVIS_BUILD_DIR}; mkdir build; cd build

script:
  - if [[ -n ${CODECOV+x} ]]; then cmake -DCMAKE_BUILD_TYPE=Debug ..;
    else cmake ..; fi;
  - make -j
  - if [[ -z ${NO_BOOST+x} ]]; then ctest -V; fi

after_success:
  - if [[ -n ${CODECOV+x} ]]; then ${TRAVIS_BUILD_DIR}/script/travis_post_codecov.sh; fi
