language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode12
      name: "osx xcode 12"

    - os: linux
      dist: focal
      name: "linux with boost"
      addons:
        apt:
          packages: ['libboost-system1.71-dev', 'libboost-test1.71-dev', 'libboost-program-options1.71-dev', 'libcurl4-openssl-dev']

    - os: linux
      dist: focal
      name: "linux without boost"
      env: NO_BOOST=true

    - os: linux
      dist: focal
      name: "conan with boost"
      script:
        - script/travis_ci_conan_build.sh

    - os: linux
      dist: focal
      name: "conan without boost"
      env: NO_BOOST=true
      script:
        - script/travis_ci_conan_build.sh

    - os: linux
      dist: focal
      name: "coverage"
      env: CODECOV=true
      addons:
        apt:
          packages: ['lcov', 'libboost-system1.71-dev', 'libboost-test1.71-dev', 'libboost-program-options1.71-dev', 'libcurl4-openssl-dev']
      script:
        - mkdir build && cd build
        - cmake -DINFLUXCXX_COVERAGE=ON ..
        - make -j
        - ctest -V
      after_success:
        ${TRAVIS_BUILD_DIR}/script/travis_post_codecov.sh

install:
  - script/travis_ci_setup_influxdb.sh

script:
  - script/ci_build.sh
  - if [[ -z ${NO_BOOST+x} ]]; then cmake --build build --target test; fi
