name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - gcc-10
          - gcc-9
          - clang-11
          - clang-10
        boost:
          - true
          - false
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }} (Boost: ${{ matrix.boost }})"
    steps:
      - uses: actions/checkout@master
      - name: update package list
        run: apt-get update
      - name: Install dependencies
        run: apt-get install -y libcurl4-openssl-dev influxdb
      - name: Install Boost
        if: ${{ matrix.boost == true }}
        run: apt-get install -y libboost-system1.71-dev libboost-test1.71-dev libboost-program-options1.71-dev
      - name: Build
        run: script/ci_build.sh -DINFLUXCXX_TESTING=ON
      - name: Test
        run: script/ci_test.sh
      - name: Check deployment as cmake subdirectory
        run: script/ci_testdeploy.sh -DINFLUXCXX_AS_SUBDIR=ON
      - name: Install
        run: cmake --build build --target install
      - name: Check installed library
        run: script/ci_testdeploy.sh -DINFLUXCXX_AS_SUBDIR=OFF


  build_conan:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        boost:
          - "True"
          - "False"
    name: "Conan (Boost: ${{ matrix.boost }})"
    steps:
      - uses: actions/checkout@master
      - name: Setup
        run: |
          pip install -U conan
          echo "~/.local/bin" >> $GITHUB_PATH
      - name: Setup Conan
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Setup InfluxDB
        if: matrix.boost == 'True'
        run: |
          INFLUXDB_VERSION="1.8.3"
          wget https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VERSION}_amd64.deb
          sudo dpkg -i influxdb_${INFLUXDB_VERSION}_amd64.deb
          sudo systemctl unmask influxdb.service
          sudo systemctl start influxdb
      - name: Build
        run: conan create -o influxdb-cxx:boost=${{ matrix.boost }} -o influxdb-cxx:tests=${{ matrix.boost }} .


  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler:
          - msvc
        boost:
          - true
          - false
    name: "${{ matrix.compiler }} (Boost: ${{ matrix.boost }})"
    steps:
      - uses: actions/checkout@master
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
      - name: Setup MSVC
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install dependencies
        run: |
          pip install -U conan
          conan install -g cmake_paths -o libcurl:shared=True libcurl/7.72.0@
      - name: Build
        env:
          CC: cl
          CXX: cl
        run: |
          if [[ "${{ matrix.boost }}" == "true" ]]; then
            export BOOST_ROOT="${BOOST_ROOT_1_72_0}"
          fi
          script/ci_build.sh -DCMAKE_CXX_FLAGS_INIT=-D_WIN32_WINNT=0x0A00 -DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake -G Ninja
        shell: bash
      - name: Install
        run: cmake --build build --target install


  build_osx:
    runs-on: macOS-latest
    name: "Mac OS X"
    steps:
      - uses: actions/checkout@master
      - name: Setup
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install influxdb
          ln -sfv /usr/local/opt/influxdb/*.plist ~/Library/LaunchAgents
          launchctl load ~/Library/LaunchAgents/homebrew.mxcl.influxdb.plist
          sleep 10
          influx -execute 'CREATE DATABASE test'
      - name: Build
        run: |
          script/ci_build.sh
          cmake --build build --target test
