name: system test

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - gcc-10
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@master
      - name: Setup
        run: |
          apt-get update
          apt-get install -y python3-pip libcurl4-openssl-dev libboost-system1.71-dev libboost-test1.71-dev
          pip3 install -U conan
          if [ "${{ startsWith(matrix.compiler, 'gcc') }}" = true ]; then
            conan profile new default --detect
            conan profile update settings.compiler.libcxx=libstdc++11 default
          fi
          conan install -o influxdb-cxx:system=True -o influxdb-cxx:tests=True .
          curl https://dl.influxdata.com/influxdb/releases/influxdb_1.8.4_amd64.deb --output influxdb_1.8.4_amd64.deb
          dpkg -i influxdb_1.8.4_amd64.deb
          service influxdb start
      - name: Build
        run: |
          script/ci_build.sh -DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake
          cmake --build build --target systemtest2
